[SC-343] Disable unused code paths
marsfoundation/aave-v3-core pull request #3
Opened 2024-02-24 15:26 UTC by hexonaut

First round is to disable unused code paths to reduce attack surface. Two main changes:

 * Disable the flashloan into borrow feature. It is not used and introduces a lot of attack surface. The Jan 10th exploit was possible due to this code path.
 * Stable borrow is not activated in practice, but we explicitly revert now even if the market is configured to have it enabled.

2024-02-26 14:56 UTC, lucas-manuel commented
Remove stable reverts

2024-02-29 16:01 UTC, lucas-manuel requested changes

2024-02-29 16:01 UTC, lucas-manuel commented on contracts/protocol/libraries/logic/FlashLoanLogic.sol
> +        revert('FEATURE_DEPRECATED');
`FLASHLOAN_INTO_BORROW_DEPRECATED`

2024-02-29 16:01 UTC, lucas-manuel commented on test-suites/pool-authorized-flashloan.spec.ts
> -  it('Takes out a 500 USDC flashloan with mode = 0, does not return the funds (revert expected)', async () => {
Don't we need to keep this test? As far as I can tell we should only be removing mode = 1 and mode = 2

2024-02-29 16:01 UTC, lucas-manuel commented on test-suites/pool-flashloan.spec.ts
> -  it('Takes out a 500 USDC flashloan with mode = 0, does not return the funds (revert expected)', async () => {
Think we should keep this test as its mode 0

2024-02-29 16:46 UTC, hexonaut commented on test-suites/pool-authorized-flashloan.spec.ts
> -  it('Takes out a 500 USDC flashloan with mode = 0, does not return the funds (revert expected)', async () => {
Yes. The test is incorrectly labeled. It uses mode 2.

2024-02-29 16:46 UTC, hexonaut commented on test-suites/pool-flashloan.spec.ts
> -  it('Takes out a 500 USDC flashloan with mode = 0, does not return the funds (revert expected)', async () => {
Same here.

2024-02-29 16:48 UTC, hexonaut commented on contracts/protocol/libraries/logic/FlashLoanLogic.sol
> +        revert('FEATURE_DEPRECATED');
changed

2024-02-29 18:36 UTC, lucas-manuel approved these changes

2024-03-05 11:29 UTC, barrutko approved these changes

2024-03-06 16:20 UTC, merged